import static java.awt.Frame.MAXIMIZED_BOTH;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import java.util.HashMap;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;

/**
 *
 * @author Ramiro Oliveira Pamponet
 */
public class Principal extends javax.swing.JFrame {

    ConexaoBD con;
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
    MaskFormatter formatoData;
    HashMap parametros;
    JasperPrint jp;
    JasperViewer jrv;
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btDados = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfcodfilial = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfcodfarmacia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfcidfilial = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfrazaosocial = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfnomefilial = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfcnpj = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfie = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfuf = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfcep = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfendereco = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfbairro = new javax.swing.JTextField();
        btSair = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        try{      formatoData = new MaskFormatter("##/##/####");  }catch(Exception e){      JOptionPane.showMessageDialog(null, "Erro ao tentar aplicar a Máscara");  }
        tfDataInicial = new JFormattedTextField(formatoData);
        jLabel13 = new javax.swing.JLabel();
        try{      formatoData = new MaskFormatter("##/##/####");  }catch(Exception e){      JOptionPane.showMessageDialog(null, "Erro ao tentar aplicar a Máscara");  }
        tfDataFinal = new JFormattedTextField(formatoData);
        btPesquisar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tfMesInicial = new javax.swing.JTextField();
        tfMes1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        tfAnoInicial = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        tfMesFinal = new javax.swing.JTextField();
        tfMes2 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        tfAnoFinal = new javax.swing.JTextField();
        btPesquisar1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        tfAno1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        tfAno2 = new javax.swing.JTextField();
        btPesquisar2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        try{      formatoData = new MaskFormatter("##/##/####");  }catch(Exception e){      JOptionPane.showMessageDialog(null, "Erro ao tentar aplicar a Máscara");  }
        tfData1 = new JFormattedTextField(formatoData);
        jLabel28 = new javax.swing.JLabel();
        try{      formatoData = new MaskFormatter("##/##/####");  }catch(Exception e){      JOptionPane.showMessageDialog(null, "Erro ao tentar aplicar a Máscara");  }
        tfData2 = new JFormattedTextField(formatoData);
        btPesquisar3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        try{      formatoData = new MaskFormatter("##/##/####");  }catch(Exception e){      JOptionPane.showMessageDialog(null, "Erro ao tentar aplicar a Máscara");  }
        tfDataInicial1 = new JFormattedTextField(formatoData);
        jLabel44 = new javax.swing.JLabel();
        try{      formatoData = new MaskFormatter("##/##/####");  }catch(Exception e){      JOptionPane.showMessageDialog(null, "Erro ao tentar aplicar a Máscara");  }
        tfDataFinal1 = new JFormattedTextField(formatoData);
        btPesquisar7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel45 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        tfMesIni = new javax.swing.JTextField();
        tfMes3 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        tfAnoIni = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        tfMesFim = new javax.swing.JTextField();
        tfMes4 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        tfAnoFim = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        btPesquisar4 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        tfAno3 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        tfAno4 = new javax.swing.JTextField();
        btPesquisar5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        try{      formatoData = new MaskFormatter("##/##/####");  }catch(Exception e){      JOptionPane.showMessageDialog(null, "Erro ao tentar aplicar a Máscara");  }
        tfDataI = new JFormattedTextField(formatoData);
        jLabel41 = new javax.swing.JLabel();
        try{      formatoData = new MaskFormatter("##/##/####");  }catch(Exception e){      JOptionPane.showMessageDialog(null, "Erro ao tentar aplicar a Máscara");  }
        tfDataF = new JFormattedTextField(formatoData);
        btPesquisar6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FPB - Estatistica de Receitas 3.1");
        setResizable(false);

        btDados.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btDados.setText("Mostrar Dados");
        btDados.setFocusable(false);
        btDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDadosActionPerformed(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setFocusable(false);

        jLabel1.setText("Código Filial:");

        tfcodfilial.setEditable(false);
        tfcodfilial.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfcodfilial.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfcodfilial.setFocusable(false);

        jLabel2.setText("Código Farmacia:");

        tfcodfarmacia.setEditable(false);
        tfcodfarmacia.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfcodfarmacia.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfcodfarmacia.setFocusable(false);

        jLabel3.setText("Cidade:");

        tfcidfilial.setEditable(false);
        tfcidfilial.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfcidfilial.setFocusable(false);

        jLabel4.setText("Razão Social:");

        tfrazaosocial.setEditable(false);
        tfrazaosocial.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfrazaosocial.setFocusable(false);

        jLabel5.setText("Nome Filial:");

        tfnomefilial.setEditable(false);
        tfnomefilial.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfnomefilial.setFocusable(false);

        jLabel6.setText("CNPJ:");

        tfcnpj.setEditable(false);
        tfcnpj.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfcnpj.setFocusable(false);

        jLabel7.setText("I.E.:");

        tfie.setEditable(false);
        tfie.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfie.setFocusable(false);

        jLabel8.setText("UF:");

        tfuf.setEditable(false);
        tfuf.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfuf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfuf.setFocusable(false);

        jLabel9.setText("CEP:");

        tfcep.setEditable(false);
        tfcep.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfcep.setFocusable(false);

        jLabel10.setText("Endereço:");

        tfendereco.setEditable(false);
        tfendereco.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfendereco.setFocusable(false);

        jLabel11.setText("Bairro:");

        tfbairro.setEditable(false);
        tfbairro.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfbairro.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfendereco)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfrazaosocial, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfnomefilial))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfcnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfie)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfuf, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfcep))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfbairro, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfcodfilial, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfcodfarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfcidfilial)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfcodfilial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(tfcodfarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(tfcidfilial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfrazaosocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(tfnomefilial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfcnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(tfie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(tfuf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(tfcep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfendereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tfbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        btSair.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btSair.setText("Sair");
        btSair.setFocusable(false);
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel15.setText("Desenvolvido por Ramiro Oliveira Pamponet - Farmacêutico Gerente da Unidade FPB-Comércio - BA");
        jLabel15.setFocusable(false);

        jLabel14.setText("OBS: Dentro do Mesmo Mês ........");
        jLabel14.setFocusable(false);

        jLabel12.setText("Data Inicial:");
        jLabel12.setFocusable(false);

        tfDataInicial.requestFocus();
        tfDataInicial.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfDataInicial.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel13.setText("Data Final:");
        jLabel13.setFocusable(false);

        tfDataFinal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfDataFinal.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btPesquisar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btPesquisar.setText("Gerar Relatório");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Limpar");
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel32.setText("A partir da Instalação do Sistema POD1 versão Java.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(btPesquisar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfDataFinal, tfDataInicial});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPesquisar)
                    .addComponent(jLabel14)
                    .addComponent(jLabel12)
                    .addComponent(tfDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(tfDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel32))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Estatística Diária", jPanel2);

        jLabel16.setText("Data Inicial ....................:");
        jLabel16.setFocusable(false);

        jLabel17.setText("Data Final .....................:");
        jLabel17.setFocusable(false);

        jLabel18.setText("Mês:");

        tfMesInicial.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfMesInicial.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfMesInicial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfMesInicialFocusLost(evt);
            }
        });

        tfMes1.setEditable(false);
        tfMes1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfMes1.setFocusable(false);

        jLabel19.setText("Ano:");

        tfAnoInicial.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfAnoInicial.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel20.setText("Mês:");

        tfMesFinal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfMesFinal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfMesFinal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfMesFinalFocusLost(evt);
            }
        });

        tfMes2.setEditable(false);
        tfMes2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfMes2.setFocusable(false);

        jLabel21.setText("Ano:");

        tfAnoFinal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfAnoFinal.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btPesquisar1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btPesquisar1.setText("Gerar Relatório");
        btPesquisar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisar1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("Limpar");
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel38.setText("A partir da Instalação do Sistema POD1 versão Java.");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfMesInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfMes1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel19))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfMesFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfMes2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel21)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfAnoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfAnoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btPesquisar1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18)
                    .addComponent(tfMesInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfMes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(tfAnoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel20)
                    .addComponent(tfMesFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfMes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(tfAnoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPesquisar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jLabel38)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Estatística Mensal", jPanel4);

        jLabel22.setText("Ano Inicial:");
        jLabel22.setFocusable(false);

        tfAno1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfAno1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel24.setText("Ano Final:");
        jLabel24.setFocusable(false);

        tfAno2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfAno2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btPesquisar2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btPesquisar2.setText("Gerar Relatório");
        btPesquisar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisar2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("Limpar");
        jButton3.setFocusable(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel36.setText("A partir da Instalação do Sistema POD1 versão Java.");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(tfAno1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel36))
                .addGap(13, 13, 13)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(18, 18, 18)
                        .addComponent(tfAno2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btPesquisar2))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(27, 285, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel24)
                    .addComponent(btPesquisar2)
                    .addComponent(tfAno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAno2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jLabel36))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Estatística Anual", jPanel5);

        jLabel26.setText("OBS: Qualquer Período ................");
        jLabel26.setFocusable(false);

        jLabel27.setText("Data Inicial:");
        jLabel27.setFocusable(false);

        tfDataInicial.requestFocus();
        tfData1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfData1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel28.setText("Data Final:");
        jLabel28.setFocusable(false);

        tfData2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfData2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btPesquisar3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btPesquisar3.setText("Gerar Relatório");
        btPesquisar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisar3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("Limpar");
        jButton4.setFocusable(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel29.setText("A partir da Instalação do Sistema POD1 versão Java.");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfData1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfData2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(btPesquisar3))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPesquisar3)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(tfData1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(tfData2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jLabel29))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Análise Percentual", jPanel6);

        jLabel42.setText("OBS: Dentro do Mesmo Mês ........");
        jLabel42.setFocusable(false);

        jLabel43.setText("Data Inicial:");
        jLabel43.setFocusable(false);

        tfDataInicial.requestFocus();
        tfDataInicial1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfDataInicial1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel44.setText("Data Final:");
        jLabel44.setFocusable(false);

        tfDataFinal1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfDataFinal1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btPesquisar7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btPesquisar7.setText("Gerar Relatório");
        btPesquisar7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisar7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton8.setText("Limpar");
        jButton8.setFocusable(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel45.setText("Para atendimentos anterores à Instalação do Sistema POD1 versão JAVA.");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel42)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel43)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDataInicial1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel44)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfDataFinal1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(btPesquisar7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel45)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPesquisar7)
                    .addComponent(jLabel42)
                    .addComponent(jLabel43)
                    .addComponent(tfDataInicial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel44)
                    .addComponent(tfDataFinal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jLabel45))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 694, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Atendimentos Diário", jPanel3);

        jLabel30.setText("Mês:");

        tfMesIni.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfMesIni.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfMesIni.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfMesIniFocusLost(evt);
            }
        });

        tfMes3.setEditable(false);
        tfMes3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfMes3.setFocusable(false);

        jLabel31.setText("Ano:");

        tfAnoIni.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfAnoIni.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel33.setText("Mês:");

        tfMesFim.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfMesFim.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfMesFim.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfMesFimFocusLost(evt);
            }
        });

        tfMes4.setEditable(false);
        tfMes4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfMes4.setFocusable(false);

        jLabel34.setText("Ano:");

        tfAnoFim.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfAnoFim.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setText("Limpar");
        jButton5.setFocusable(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        btPesquisar4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btPesquisar4.setText("Gerar Relatório");
        btPesquisar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisar4ActionPerformed(evt);
            }
        });

        jLabel23.setText("Data Inicial ....................:");
        jLabel23.setFocusable(false);

        jLabel25.setText("Data Final .....................:");
        jLabel25.setFocusable(false);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfMesIni, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfMes3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfAnoIni, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfMesFim, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfMes4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfAnoFim, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPesquisar4))
                .addGap(169, 169, 169))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(tfMes3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfMesIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31)
                            .addComponent(tfAnoIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(jLabel33)
                            .addComponent(tfMesFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfMes4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34)
                            .addComponent(tfAnoFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btPesquisar4))))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Atendimentos Mensal", jPanel7);

        jLabel35.setText("Ano Inicial:");
        jLabel35.setFocusable(false);

        tfAno3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfAno3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel37.setText("Ano Final:");
        jLabel37.setFocusable(false);

        tfAno4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfAno4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btPesquisar5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btPesquisar5.setText("Gerar Relatório");
        btPesquisar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisar5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton6.setText("Limpar");
        jButton6.setFocusable(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35)
                .addGap(18, 18, 18)
                .addComponent(tfAno3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel37)
                        .addGap(18, 18, 18)
                        .addComponent(tfAno4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btPesquisar5))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(27, 285, Short.MAX_VALUE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jLabel37)
                    .addComponent(btPesquisar5)
                    .addComponent(tfAno3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAno4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 694, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 103, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 694, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 103, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Atendimentos Anual", jPanel8);

        jLabel39.setText("OBS: Qualquer Período ................");
        jLabel39.setFocusable(false);

        jLabel40.setText("Data Inicial:");
        jLabel40.setFocusable(false);

        tfDataInicial.requestFocus();
        tfDataI.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfDataI.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel41.setText("Data Final:");
        jLabel41.setFocusable(false);

        tfDataF.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfDataF.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btPesquisar6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btPesquisar6.setText("Gerar Relatório");
        btPesquisar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisar6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton7.setText("Limpar");
        jButton7.setFocusable(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDataI, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel41)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfDataF, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(btPesquisar6))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPesquisar6)
                    .addComponent(jLabel39)
                    .addComponent(jLabel40)
                    .addComponent(tfDataI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41)
                    .addComponent(tfDataF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Máximo e Mínimo", jPanel9);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btDados)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                        .addGap(58, 58, 58))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDados)
                    .addComponent(btSair))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(727, 453));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDadosActionPerformed
        try {
            con = new ConexaoBD();
            String sql = "select distinct f.cod_filial, f.cod_farmacia,  f.raz_social,  "
                    + "f.nom_filial,  f.num_cnpj,  f.num_inscest,   f.end_filial,   "
                    + "f.bai_filial, f.cid_filial,  f.cep_filial,  f.est_filial from "
                    + "cadfilia f, cadcvend v where v.cod_filial=f.cod_filial";
            con.conecta();
            con.executeSQL(sql);
            con.rs.first();
            mostraDados();
        } catch (Exception e) {
            e.printStackTrace();
        }finally{
            con.desonecta();
        }
    }//GEN-LAST:event_btDadosActionPerformed
    
    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btSairActionPerformed
    
    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
            try {
                con = new ConexaoBD();
                parametros = new HashMap();
                parametros.put("data_ini", sdf.parse(tfDataInicial.getText()));
                parametros.put("data_fim", sdf.parse(tfDataFinal.getText()));
                jp = JasperFillManager.fillReport("./Relatorios/receitas.jasper", 
parametros, con.conecta());
                jrv = new JasperViewer(jp, false);
                jrv.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                jrv.setVisible(true);                
                jrv.setExtendedState(MAXIMIZED_BOTH);             

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao Tentar Imprimir Relatório.");
                e.printStackTrace();
            }finally{
                con.desonecta();
            }            
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        tfDataInicial.setText("");
        tfDataFinal.setText("");
        tfDataInicial.requestFocus();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btPesquisar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisar1ActionPerformed
            try {
                con = new ConexaoBD();
                parametros = new HashMap();
                parametros.put("mes_ini", Double.parseDouble(tfMesInicial.getText()));                
                parametros.put("ano_ini", Double.parseDouble(tfAnoInicial.getText()));
                parametros.put("mes_fim", Double.parseDouble(tfMesFinal.getText()));
                parametros.put("ano_fim", Double.parseDouble(tfAnoFinal.getText()));
                jp = JasperFillManager.fillReport("./Relatorios/recmensal.jasper", 
parametros, con.conecta());
                jrv = new JasperViewer(jp, false);
                jrv.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                jrv.setVisible(true);
                jrv.setExtendedState(MAXIMIZED_BOTH);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao Tentar Imprimir Relatório.");
                e.printStackTrace();
            }finally{
                con.desonecta();
            }
    }//GEN-LAST:event_btPesquisar1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        tfMesInicial.setText("");
        tfMes1.setText("");
        tfAnoInicial.setText("");
        tfMesFinal.setText("");
        tfMes2.setText("");
        tfAnoFinal.setText("");
        tfMesInicial.requestFocus();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btPesquisar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisar2ActionPerformed
            try {
                con = new ConexaoBD();
                parametros = new HashMap();
                parametros.put("ano_ini", Double.parseDouble(tfAno1.getText()));
                parametros.put("ano_fim", Double.parseDouble(tfAno2.getText()));
                jp = JasperFillManager.fillReport("./Relatorios/recanual.jasper", 
parametros, con.conecta());
                jrv = new JasperViewer(jp, false);
                jrv.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                jrv.setVisible(true);
                jrv.setExtendedState(MAXIMIZED_BOTH);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao Tentar Imprimir Relatório.");
                e.printStackTrace();
            }finally{
                con.desonecta();
            }
    }//GEN-LAST:event_btPesquisar2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        tfAno1.setText("");
        tfAno2.setText("");
        tfAno1.requestFocus();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btPesquisar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisar3ActionPerformed
            try {
                con = new ConexaoBD();
                parametros = new HashMap();
                parametros.put("data_ini", sdf.parse(tfData1.getText()));
                parametros.put("data_fim", sdf.parse(tfData2.getText()));
                jp = JasperFillManager.fillReport("./Relatorios/percentual.jasper", 
parametros, con.conecta());
                jrv = new JasperViewer(jp, false);
                jrv.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                jrv.setVisible(true);
                jrv.setExtendedState(MAXIMIZED_BOTH);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao Tentar Imprimir Relatório.");
                e.printStackTrace();
            }finally{
                con.desonecta();
            }
    }//GEN-LAST:event_btPesquisar3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        tfData1.setText("");
        tfData2.setText("");
        tfData1.requestFocus();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        tfMesIni.setText("");
        tfMes3.setText("");
        tfAnoIni.setText("");
        tfMesFim.setText("");
        tfMes4.setText("");
        tfAnoFim.setText("");
        tfMesIni.requestFocus();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btPesquisar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisar4ActionPerformed
            try {
                con = new ConexaoBD();
                parametros = new HashMap();
                parametros.put("mes_ini", Double.parseDouble(tfMesIni.getText()));
                parametros.put("ano_ini", Double.parseDouble(tfAnoIni.getText()));
                parametros.put("mes_fim", Double.parseDouble(tfMesFim.getText()));
                parametros.put("ano_fim", Double.parseDouble(tfAnoFim.getText()));
                jp = JasperFillManager.fillReport("./Relatorios/atendmensal.jasper", 
parametros, con.conecta());
                jrv = new JasperViewer(jp, false);
                jrv.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                jrv.setVisible(true);
                jrv.setExtendedState(MAXIMIZED_BOTH);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao Tentar Imprimir Relatório.");
                e.printStackTrace();
            }finally{
                con.desonecta();
            }
    }//GEN-LAST:event_btPesquisar4ActionPerformed

    private void btPesquisar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisar6ActionPerformed
            try {
                con = new ConexaoBD();
                parametros = new HashMap();
                parametros.put("data_ini", sdf.parse(tfDataI.getText()));
                parametros.put("data_fim", sdf.parse(tfDataF.getText()));
                jp = JasperFillManager.fillReport("./Relatorios/maxmin.jasper", 
parametros, con.conecta());
                jrv = new JasperViewer(jp, false);
                jrv.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                jrv.setVisible(true);
                jrv.setExtendedState(MAXIMIZED_BOTH);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao Tentar Imprimir Relatório.");
                e.printStackTrace();
            }finally{
                con.desonecta();
            }
    }//GEN-LAST:event_btPesquisar6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        tfDataI.setText("");
        tfDataF.setText("");
        tfDataI.requestFocus();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void tfMesInicialFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfMesInicialFocusLost
        if(tfMesInicial.getText().equals("")){
            
        }else if(tfMesInicial.getText().equals("1")){
            tfMes1.setText("JANEIRO");
        }else if(tfMesInicial.getText().equals("2")){
            tfMes1.setText("FEVEREIRO");
        }else if(tfMesInicial.getText().equals("3")){
            tfMes1.setText("MARÇO");
        }else if(tfMesInicial.getText().equals("4")){
            tfMes1.setText("ABRIL");
        }else if(tfMesInicial.getText().equals("5")){
            tfMes1.setText("MAIO");
        }else if(tfMesInicial.getText().equals("6")){
            tfMes1.setText("JUNHO");
        }else if(tfMesInicial.getText().equals("7")){
            tfMes1.setText("JULHO");
        }else if(tfMesInicial.getText().equals("8")){
            tfMes1.setText("AGOSTO");
        }else if(tfMesInicial.getText().equals("9")){
            tfMes1.setText("SETEMBRO");
        }else if(tfMesInicial.getText().equals("10")){
            tfMes1.setText("OUTUBRO");
        }else if(tfMesInicial.getText().equals("11")){
            tfMes1.setText("NOVEMBRO");
        }else if(tfMesInicial.getText().equals("12")){
            tfMes1.setText("DEZEMBRO");
        }else{
            JOptionPane.showMessageDialog(rootPane, "Digite um número entre 1 e 12.");
            tfMesInicial.requestFocus();
        }
    }//GEN-LAST:event_tfMesInicialFocusLost

    private void btPesquisar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisar5ActionPerformed
            try {
                con = new ConexaoBD();
                parametros = new HashMap();
                parametros.put("ano_ini", Double.parseDouble(tfAno3.getText()));
                parametros.put("ano_fim", Double.parseDouble(tfAno4.getText()));
                jp = JasperFillManager.fillReport("./Relatorios/atendanual.jasper", 
parametros, con.conecta());
                jrv = new JasperViewer(jp, false);
                jrv.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                jrv.setVisible(true);
                jrv.setExtendedState(MAXIMIZED_BOTH);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao Tentar Imprimir Relatório.");
                e.printStackTrace();
            }finally{
                con.desonecta();
            }
    }//GEN-LAST:event_btPesquisar5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        tfAno3.setText("");
        tfAno4.setText("");
        tfAno3.requestFocus();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void tfMesFinalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfMesFinalFocusLost
        if(tfMesFinal.getText().equals("")){
            
        }else if(tfMesFinal.getText().equals("1")){
            tfMes2.setText("JANEIRO");
        }else if(tfMesFinal.getText().equals("2")){
            tfMes2.setText("FEVEREIRO");
        }else if(tfMesFinal.getText().equals("3")){
            tfMes2.setText("MARÇO");
        }else if(tfMesFinal.getText().equals("4")){
            tfMes2.setText("ABRIL");
        }else if(tfMesFinal.getText().equals("5")){
            tfMes2.setText("MAIO");
        }else if(tfMesFinal.getText().equals("6")){
            tfMes2.setText("JUNHO");
        }else if(tfMesFinal.getText().equals("7")){
            tfMes2.setText("JULHO");
        }else if(tfMesFinal.getText().equals("8")){
            tfMes2.setText("AGOSTO");
        }else if(tfMesFinal.getText().equals("9")){
            tfMes2.setText("SETEMBRO");
        }else if(tfMesFinal.getText().equals("10")){
            tfMes2.setText("OUTUBRO");
        }else if(tfMesFinal.getText().equals("11")){
            tfMes2.setText("NOVEMBRO");
        }else if(tfMesFinal.getText().equals("12")){
            tfMes2.setText("DEZEMBRO");
        }else{
            JOptionPane.showMessageDialog(rootPane, "Digite um número entre 1 e 12.");
            tfMesFinal.requestFocus();
        }
    }//GEN-LAST:event_tfMesFinalFocusLost

    private void tfMesIniFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfMesIniFocusLost
        if(tfMesIni.getText().equals("")){
            
        }else if(tfMesIni.getText().equals("1")){
            tfMes3.setText("JANEIRO");
        }else if(tfMesIni.getText().equals("2")){
            tfMes3.setText("FEVEREIRO");
        }else if(tfMesIni.getText().equals("3")){
            tfMes3.setText("MARÇO");
        }else if(tfMesIni.getText().equals("4")){
            tfMes3.setText("ABRIL");
        }else if(tfMesIni.getText().equals("5")){
            tfMes3.setText("MAIO");
        }else if(tfMesIni.getText().equals("6")){
            tfMes3.setText("JUNHO");
        }else if(tfMesIni.getText().equals("7")){
            tfMes3.setText("JULHO");
        }else if(tfMesIni.getText().equals("8")){
            tfMes3.setText("AGOSTO");
        }else if(tfMesIni.getText().equals("9")){
            tfMes3.setText("SETEMBRO");
        }else if(tfMesIni.getText().equals("10")){
            tfMes3.setText("OUTUBRO");
        }else if(tfMesIni.getText().equals("11")){
            tfMes3.setText("NOVEMBRO");
        }else if(tfMesIni.getText().equals("12")){
            tfMes3.setText("DEZEMBRO");
        }else{
            JOptionPane.showMessageDialog(rootPane, "Digite um número entre 1 e 12.");
            tfMesIni.requestFocus();
        }
    }//GEN-LAST:event_tfMesIniFocusLost

    private void tfMesFimFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfMesFimFocusLost
        if(tfMesIni.getText().equals("")){
            
        }else if(tfMesFim.getText().equals("1")){
            tfMes4.setText("JANEIRO");
        }else if(tfMesFim.getText().equals("2")){
            tfMes4.setText("FEVEREIRO");
        }else if(tfMesFim.getText().equals("3")){
            tfMes4.setText("MARÇO");
        }else if(tfMesFim.getText().equals("4")){
            tfMes4.setText("ABRIL");
        }else if(tfMesFim.getText().equals("5")){
            tfMes4.setText("MAIO");
        }else if(tfMesFim.getText().equals("6")){
            tfMes4.setText("JUNHO");
        }else if(tfMesFim.getText().equals("7")){
            tfMes4.setText("JULHO");
        }else if(tfMesFim.getText().equals("8")){
            tfMes4.setText("AGOSTO");
        }else if(tfMesFim.getText().equals("9")){
            tfMes4.setText("SETEMBRO");
        }else if(tfMesFim.getText().equals("10")){
            tfMes4.setText("OUTUBRO");
        }else if(tfMesFim.getText().equals("11")){
            tfMes4.setText("NOVEMBRO");
        }else if(tfMesFim.getText().equals("12")){
            tfMes4.setText("DEZEMBRO");
        }else{
            JOptionPane.showMessageDialog(rootPane, "Digite um número entre 1 e 12.");
            tfMesFim.requestFocus();
        }
    }//GEN-LAST:event_tfMesFimFocusLost

    private void btPesquisar7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisar7ActionPerformed
            try {
                con = new ConexaoBD();
                parametros = new HashMap();
                parametros.put("data_ini", sdf.parse(tfDataInicial1.getText()));
                parametros.put("data_fim", sdf.parse(tfDataFinal1.getText()));
                jp = JasperFillManager.fillReport("./Relatorios/atendimentos.jasper", 
parametros, con.conecta());
                jrv = new JasperViewer(jp, false);
                jrv.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                jrv.setVisible(true);                
                jrv.setExtendedState(MAXIMIZED_BOTH);             

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao Tentar Imprimir Relatório.");
                e.printStackTrace();
            }finally{
                con.desonecta();
            }
    }//GEN-LAST:event_btPesquisar7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       tfDataInicial1.setText("");
       tfDataFinal1.setText("");
       tfDataInicial1.requestFocus();
    }//GEN-LAST:event_jButton8ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Principal().setVisible(true);
            }
        });
            
    }

    private void mostraDados() throws SQLException {
        if (con.rs.first()) {
            tfcodfilial.setText(con.rs.getString("cod_filial"));
            tfcodfarmacia.setText(con.rs.getString("cod_farmacia"));
            tfrazaosocial.setText(con.rs.getString("raz_social"));
            tfnomefilial.setText(con.rs.getString("nom_filial"));
            tfcnpj.setText(con.rs.getString("num_cnpj"));
            tfie.setText(con.rs.getString("num_inscest"));
            tfendereco.setText(con.rs.getString("end_filial"));
            tfbairro.setText(con.rs.getString("bai_filial"));
            tfcidfilial.setText(con.rs.getString("cid_filial"));
            tfcep.setText(con.rs.getString("cep_filial"));
            tfuf.setText(con.rs.getString("est_filial"));
        } else {
            JOptionPane.showMessageDialog(null, "Não Localizou Dados!");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDados;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btPesquisar1;
    private javax.swing.JButton btPesquisar2;
    private javax.swing.JButton btPesquisar3;
    private javax.swing.JButton btPesquisar4;
    private javax.swing.JButton btPesquisar5;
    private javax.swing.JButton btPesquisar6;
    private javax.swing.JButton btPesquisar7;
    private javax.swing.JButton btSair;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField tfAno1;
    private javax.swing.JTextField tfAno2;
    private javax.swing.JTextField tfAno3;
    private javax.swing.JTextField tfAno4;
    private javax.swing.JTextField tfAnoFim;
    private javax.swing.JTextField tfAnoFinal;
    private javax.swing.JTextField tfAnoIni;
    private javax.swing.JTextField tfAnoInicial;
    private javax.swing.JTextField tfData1;
    private javax.swing.JTextField tfData2;
    private javax.swing.JTextField tfDataF;
    private javax.swing.JTextField tfDataFinal;
    private javax.swing.JTextField tfDataFinal1;
    private javax.swing.JTextField tfDataI;
    private javax.swing.JTextField tfDataInicial;
    private javax.swing.JTextField tfDataInicial1;
    private javax.swing.JTextField tfMes1;
    private javax.swing.JTextField tfMes2;
    private javax.swing.JTextField tfMes3;
    private javax.swing.JTextField tfMes4;
    private javax.swing.JTextField tfMesFim;
    private javax.swing.JTextField tfMesFinal;
    private javax.swing.JTextField tfMesIni;
    private javax.swing.JTextField tfMesInicial;
    private javax.swing.JTextField tfbairro;
    private javax.swing.JTextField tfcep;
    private javax.swing.JTextField tfcidfilial;
    private javax.swing.JTextField tfcnpj;
    private javax.swing.JTextField tfcodfarmacia;
    private javax.swing.JTextField tfcodfilial;
    private javax.swing.JTextField tfendereco;
    private javax.swing.JTextField tfie;
    private javax.swing.JTextField tfnomefilial;
    private javax.swing.JTextField tfrazaosocial;
    private javax.swing.JTextField tfuf;
    // End of variables declaration//GEN-END:variables
}